
export const ADD_CURRENCY_EXCHANGE_RATE = "ADD_CURRENCY_EXCHANGE_RATE"
export const REMOVE_CURRENCY_EXCHANGE_RATE = "REMOVE_CURRENCY_EXCHANGE_RATE"
export const SET_CURRENCIES_RATE = "SET_CURRENCIES_RATE"
export const SET_BASE_CURRENCY_VALUE = "SET_BASE_CURRENCY_VALUE"